name: Add New Data

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [add-new-data]

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas==2.3.1 numpy==2.0.2 requests lxml html5lib bs4 cloudscraper duckdb

      - name: Execute Create NBA Schedule notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/create_nba_schedule.ipynb"

      - name: Execute gamelog_retriever notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/gamelog_retriever.ipynb"

      - name: Execute Create Player Pos Xref notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/create_plyr_pos_xref.ipynb"

      - name: Execute parlay helper notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/parlay helper.ipynb"

      - name: Commit updated CSVs back to repository
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git checkout main

          git add tables/2025/*.csv

          git status

          git diff --cached --quiet || git commit -m "Auto-update GHA: add_new_data ($(date -u +"%Y-%m-%d"))"

          git push origin main