name: Run Jupyter Notebook

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-tables]

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas numpy requests nbainjuries duckdb lxml html5lib bs4 cloudscraper nbdime

      - name: Execute gamelog_retriever notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/gamelog_retriever.ipynb"
        continue-on-error: true

      - name: Execute parlay helper notebook
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=python3 \
            "notebooks/parlay helper.ipynb"

      # - name: Execute parlay actuals notebook
      #   run: |
      #     jupyter nbconvert \
      #       --to notebook \
      #       --execute \
      #       --inplace \
      #       --ExecutePreprocessor.timeout=600 \
      #       --ExecutePreprocessor.kernel_name=python3 \
      #       "notebooks/parlay actuals.ipynb"

      - name: Commit updated CSVs back to repository
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git checkout main

          git add tables/2025/*.csv

          git status

          git diff --cached --quiet || git commit -m "Auto-update parlay CSV tables (GitHub Actions)"

          git push origin main